### ISSUE TITLE
Datenbank

### ISSUE THREAD

**Issue by foldericon** [FI15a-Team1/BoardGames#1]
Ich habe mal den Export der Datenbank hinzugefügt in 3fc363b7
Bitte alle Änderungen hier vermerken.

**Comment by JenniO** [comment]
wrong data type in table **offer**

must be

  `title_en` varchar(150) NOT NULL,
  `title_de` varchar(150) NOT NULL,
  
instead of
   
  `title_en` int(11) NOT NULL,
  `title_de` int(11) NOT NULL,

**Comment by aweb3r** [comment]
Ich war dann mal so frei das Impressum in die Datenbank zu kleben.

**Comment by JenniO** [comment]
in der offer Tabelle ist jetzt die article_id drin, also keine Bundles, weil ich keine Ahnung habe, wie man das machen könnte
tax Tabelle ist dazu gekommen
article hat jetzt tax_id Spalte

**Comment by Mice-Elf** [comment]
customer_confirmation: renamed some fields, added some others
newsletter_confirmation: renamed some fields
removed NOT_NULL from the ...confirmed fields in newsletter_confirmation and customer_confirmation
removed NOT_NULL from a lot of fields in customer

**Comment by foldericon** [comment]
tax_id auf 1 gesetzt für alle artikel

**Comment by Mice-Elf** [comment]
Moved customer password to separate table
Created table customer_confirmation_password for passwords of not yet confirmed accounts
Set DRI for both

**Comment by Mice-Elf** [comment]
Set length of password fields to 128

Updated data to include hashed passwords

**Comment by foldericon** [comment]
I just set AUTO_INCREMENT on a lot of ID fields for consistency because it was missing.
I couldn't do it on customer_password due to DRI constraints.
See a54486b
Please review @Mice-Elf

**Comment by Mice-Elf** [comment]
Added "deactivated" and "confirmed" to newsletter_confirmation, renamed some other fields in same table

**Comment by Mice-Elf** [comment]
checked auto-increments @foldericon

**Comment by Mice-Elf** [comment]
Added cascades to password tables

**Comment by Mice-Elf** [comment]
Sind in der .sql-Datei die "... if exists"-Teile wieder rausgenommen worden oder übersehe ich da was?

**Comment by foldericon** [comment]
Ja, weil mit Export von phpmyadmin überschrieben
