### ISSUE TITLE
Vorgehensmodell mit zeitlicher Gliederung

### ISSUE THREAD

**Issue by foldericon** [FI15a-Team1/BoardGames#10]
Das Wasserfallmodell ist ein lineares (nicht iteratives) Vorgehensmodell das in Phasen organisiert wird. Dabei gehen die Phasenergebnisse wie bei einem Wasserfall immer als bindende Vorgaben für die nächsttiefere Phase ein. Im Wasserfallmodell hat jede Phase vordefinierte Start- und Endpunkte mit eindeutig definierten Ergebnissen. Zu den wichtigsten Dokumenten zählen dabei das Lastenheft sowie das Pflichtenheft. Das Wasserfallmodell wird allgemein vorteilhaft angewendet, wenn sich Anforderungen, Leistungen und Abläufe bereits in der Planungsphase relativ präzise beschreiben lassen.
Wir haben uns für die erweiterte Wasserfallmodell entschieden, da es das einfache Wasserfallmodell um iterative Aspekte erweitert und ein schrittweises Aufwärtslaufen der Kaskade ermöglicht sofern in der aktuellen Phase etwas schieflaufen sollte, um den Fehler auf der nächsthöheren Stufe beheben zu können.
 
![Wasserfallmodell](https://i.imgur.com/mNRfxOQ.png)
Abbildung 1: Das Wasserfallmodell im Projektmanagement

**Comment by Mice-Elf** [comment]
Ich würde noch darauf hinweisen, dass das Wasserfallmodell sich anbietet, wenn die Anforderungen bereits im Vorhinein feststehen (i.U. zur Agilen Entwicklung).

**Comment by foldericon** [comment]
editiert

**Comment by foldericon** [comment]
Bild eingefügt (lässt sich leider nicht kleiner darstellen)

**Comment by Mice-Elf** [comment]
Das Bild zeigt aber nicht das *erweiterte* Wasserfallmodell, oder?

**Comment by JenniO** [comment]
Nee, nicht wirklich.
Das sollte es tun:


http://blog.flagbit.de/wp-content/uploads/2011/05/Wasserfallmodell.png
