### ISSUE TITLE
Code-Conventions

### ISSUE THREAD

**Issue by foldericon** [FI15a-Team1/BoardGames#12]
**Einrückung und Klammerung** 
Anweisungen sollten mittels Tabulatoren eingerückt werden. Eine konsistente Tabulatorgröße von 4 sollte für die Einrückung innerhalb einer Anwendung verwendet werden. Tabulatoren sollten nicht durch entsprechende Leerzeichen ersetzt werden. Die Einrückungen sollten einen Ausführungsbereich kennzeichnen.
Geschweifte Klammern sollten auch bei einzeiligen if-Anweisungen verwendet werden.
Vor öffnenden, geschweiften Klammern sollte kein Zeilenumbruch gemacht werden.
Schließende, geschweifte Klammern stehen immer auf einer neuen Zeile es sei denn es ist Teil eines zusammenhängenden if, else if, else bzw if, else – Block.

**Comment by Mice-Elf** [comment]
Sprache und Bezeichner
Sprache für Kommentare und Bezeichner ist englisch.
Methoden- und Packagebezeichner werden am Anfang klein geschrieben, Klassenbezeichner groß.
Einzelne Worte in o.g. Bezeichnern werden durch CamelCase hervorgehoben.
Bezeichner von Konstanten werden komplett in Großbuchstaben geschrieben, einzelne Worte hierbei durch Unterstrich getrennt.
Maximale Zeilenlänge
Die maximale Zeilenlänge beträgt 120 Zeichen.
