### ISSUE TITLE
Javadoc

### ISSUE THREAD

**Issue by Mice-Elf** [FI15a-Team1/BoardGames#2]
Wie formulieren wir die Javadocs-Kommentare? Insbesondere: soll die Beschreibung z.B. einer Methode imperativ oder deskriptiv sein? Also "Get locale for this user" (Befehl, was die Methode tun soll) oder "Gets locale for this user" (Beschreibung, was die Methode tut).

Aus Gewohnheitsgründen würde ich imperativ bevorzugen.

**Comment by foldericon** [comment]
Ich denke jeder wie er will aber du kannst dir ja mal anschauen wie ich es gemacht habe in 600271f
und entscheiden ob du das so für dich als sinnvoll erachtest oder nicht.
Auf jeden Fall bin ich der Meinung dass man Dinge die offensichtlich sind oder sich automatisch ergeben (wie z.B. die Felder in Article.java) nicht extra dokumentieren muss.

**Comment by Mice-Elf** [comment]
Ja, ich hab inzwischen auch noch mal geguckt und gesehen, dass im Java-Sourcecode ja auch die beschreibende Variante genommen wird.
