### ISSUE TITLE
Wirtschaftlichkeit

### ISSUE THREAD

**Issue by JenniO** [FI15a-Team1/BoardGames#5]
Durch Erstellen eines Onlineshops muss die BoardGames GmbH weniger Zeit aufwenden, um Bestellungen per Telefon oder Brief entgegenzunehmen. 
Durch die automatische Überprüfung der Bankverbindungs- und Kreditkartendaten der Kunden können hier Übertragungsfehler weitgehend verhindert werden. Dies gilt ebenso für die Bezahlung per Vorkasse, bei der der Kunde die Bankdaten der BoardGames GmbH, die der Kunde direkt auf dem Bildschirm sieht und kopieren kann und nicht per Telefon übermittelt bekommt. Dies führt zu weniger Fehlüberweisungen.
Die Übermittlung der Adresse per Telefon ist ebenfalls sehr fehleranfällig, da der Mitarbeiter sich verhören kann, oder beim Notieren die Adresse falsch aufschreiben kann. Auch kann die korrekt notierte Adresse später bei der Adressierung der Pakete noch einmal falsch gelesen oder übertragen werden. Das Eintragen der Adresse vom Kunden wird die Fehlerzahl vermindern, da der Kunde die Korrektheit direkt überprüfen kann. So kann die Häufigkeit von unzustellbaren Lieferungen wegen fehlerhafter Adressangaben vermindert werden.

**Comment by Mice-Elf** [comment]
ergänzt:
Die Hürde für den Einkauf kann durch eine Bestellung per Internet für manche Käuferschichten erheblich gesenkt werden.
Durch den Versand von Newslettern kann die Kundenbindung erhöht und die Werbewirkung von neuen Produkten und Angeboten kostengünstig deutlich gesteigert werden.
