### ISSUE TITLE
Ist-Aufnahme

### ISSUE THREAD

**Issue by foldericon** [FI15a-Team1/BoardGames#7]
> Der Kunde führt ein Ladengeschäft in dem er Brettspiele an Laufkundschaft verkauft. Bestellungen aus der Ferne lassen sich nur telefonisch oder schriftlich durchführen. Seine Geschäftszeiten beschränken sich auf 8 Stunden an Werktagen und 4 Stunden an Samstagen.

Anmerkungen?

**Comment by Mice-Elf** [comment]
Kunde durch Auftraggeber ersetzt ;-)
