### ISSUE TITLE
Projektumfeld

### ISSUE THREAD

**Issue by foldericon** [FI15a-Team1/BoardGames#9]
Unser Kunde ist die BoardGames GmbH welche klassische Brettspiele verkauft. Gerne hätte er eine Internetpräsenz bei der man auch online Bestellungen aufnehmen kann. Außerdem braucht er eine einfache Möglichkeit Kundendaten erfassen und verwalten zu können. Seine Kunden sollen im bekannten Stil Artikel in einem digitalen Warenkorb hinzufügen können und später nach Beendigung der Artikelauswahl bestellen können.

**Comment by Mice-Elf** [comment]
meine Version:
Auftraggeber ist die BoardGames GmbH, welche klassische Brettspiele verkauft. Gerne hätte sie eine Internetpräsenz bei der man auch online Bestellungen aufnehmen kann. Außerdem braucht sie eine einfache Möglichkeit, um Kundendaten erfassen und verwalten zu können. Ihre Kunden sollen im bekannten Stil Artikel in einem digitalen Warenkorb hinzufügen können und später nach Beendigung der Artikelauswahl bestellen können.

**Comment by foldericon** [comment]
¯\_(ツ)_/¯

**Comment by foldericon** [comment]
Hinzugefügt:

> Des Weiteren soll es zeitlich begrenzte Angebote auf bestimmte Artikel geben. Eine Suche, in der Benutzer nach bestimmten Artikeln suchen kann soll das Shopsystem verfeinern und gezieltere Anfragen ermöglichen. Bezahlt werden soll mit Kreitkarte, Per Nachnahme, Vorkasse oder SEPA Lastschriftmandat.
